repos:
-   repo: local
    hooks:
      -   id: rust-linting
          name: Rust linting
          description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
          entry: cargo +nightly fmt --all --
          pass_filenames: true
          types: [file, rust]
          language: system
      -   id: rust-taplo
          name: Toml linting
          description: Run taplo fmt on files included in the commit
          entry: taplo format
          pass_filenames: true
          types: [file, toml]
          language: system
      -   id: cargo-check
          name: cargo check
          description: Check the package for errors.
          entry: cargo check --tests
          language: system
          types: [ file, rust ]
          pass_filenames: false